name: Build and Deploy Jekyll site

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - uses: actions/checkout@v3

      # Step 2: Setup Ruby 2.7 with bundler cache
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      # Step 3: Update RubyGems (avoids ffi incompatibility)
      - name: Update RubyGems
        run: gem update --system

      # Step 4: Install dependencies from Gemfile
      - name: Install dependencies
        run: bundle install

      # Step 5: Build the Jekyll site
      - name: Build site
        run: bundle exec jekyll build --trace

      # Step 6: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
